"""add categories table

Revision ID: 0fd211cd256a
Revises: 4505a2807c19
Create Date: 2026-06-09 15:41:52.999328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fd211cd256a"
down_revision: Union[str, Sequence[str], None] = "4505a2807c19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.Column("spent", sa.Float(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_profiles_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    op.alter_column(
        "engine_results",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "engine_results",
        "run_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_engine_results_created_at"),
        "engine_results",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engine_results_engine_name"),
        "engine_results",
        ["engine_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_engine_results_id"), "engine_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_engine_results_run_id"), "engine_results", ["run_id"], unique=False
    )
    op.drop_constraint(
        op.f("engine_results_run_id_fkey"), "engine_results", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "engine_results",
        "financial_analysis_runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "financial_analysis_runs",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_financial_analysis_runs_created_at"),
        "financial_analysis_runs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_analysis_runs_id"),
        "financial_analysis_runs",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_analysis_runs_user_id"),
        "financial_analysis_runs",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("financial_analysis_runs_user_id_fkey"),
        "financial_analysis_runs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "financial_analysis_runs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_constraint(None, "financial_analysis_runs", type_="foreignkey")
    op.create_foreign_key(
        op.f("financial_analysis_runs_user_id_fkey"),
        "financial_analysis_runs",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_financial_analysis_runs_user_id"), table_name="financial_analysis_runs"
    )
    op.drop_index(
        op.f("ix_financial_analysis_runs_id"), table_name="financial_analysis_runs"
    )
    op.drop_index(
        op.f("ix_financial_analysis_runs_created_at"),
        table_name="financial_analysis_runs",
    )
    op.alter_column(
        "financial_analysis_runs",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "engine_results", type_="foreignkey")
    op.create_foreign_key(
        op.f("engine_results_run_id_fkey"),
        "engine_results",
        "financial_analysis_runs",
        ["run_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_engine_results_run_id"), table_name="engine_results")
    op.drop_index(op.f("ix_engine_results_id"), table_name="engine_results")
    op.drop_index(op.f("ix_engine_results_engine_name"), table_name="engine_results")
    op.drop_index(op.f("ix_engine_results_created_at"), table_name="engine_results")
    op.alter_column(
        "engine_results",
        "run_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "engine_results",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("merchant", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transactions_pkey")),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("country", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("timezone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("employment_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "monthly_income",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("risk_tolerance", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "investment_experience", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("profiles_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profiles_pkey")),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_index(op.f("ix_profiles_id"), "profiles", ["id"], unique=False)
    op.drop_table("categories")
    # ### end Alembic commands ###
